### ISSUE TITLE
pydbow3

### ISSUE THREAD

**Issue by mohcenaouadj** [eriksandstroem/Loopy-SLAM#2]
Hello, great work, I read the paper yesterday and I planned to test the model today.

This is not a real issue but just there's a missing module "**ModuleNotFoundError: No module named 'pydbow3**'", since there's many sources from where we can install it (like for example: https://github.com/foxis/pyDBoW3) I was wondering if there's a precise configuration before installing or after to make everything works smoothly.

Again, great work.

**Comment by FaSch87** [comment]
Hi, I think you can use [this one](https://github.com/notchla/PyDBoW3). It was noted in the Installation section towards the end of the instructions, so this should be the correct one.
